[profile.default]
src = 'src'
test = 'tests'
script = 'scripts'
out = 'out'
libs = ['lib']
remappings = [
]
fs_permissions = [{ access = "write", path = "./reports" }]

[rpc_endpoints]
zksync-sepolia = "${RPC_ZKSYNC_SEPOLIA}"

# See more config options https://github.com/gakonst/foundry/tree/master/config
